---  # three dashes starts the yaml file
# Template for the config file

# Paths
paths:
      - key: "test_00" # for filenames mainly now..
      - projectPath: '/Users/theresasawi/Documents/12_Projects/Parkfield_Repeaters/'
      - pathCat: '/Users/theresasawi/Documents/12_Projects/Parkfield_Repeaters/data_raw/catall.txt'
      - pathWF: '/Users/theresasawi/Documents/12_Projects/Parkfield_Repeaters/data_raw/BAV.waves/'
      - h5name: 'test_00.h5' # if we want it to be different from the key !

# Raw data parameters
dataParams:
      - network: 'NC'
      - station: 'BAV'
      - channel: 'EHZ'
      - channel_ID: 0 # the index number for an obspy stream object
      - sampling_rate: 100
      - filetype: '.mseed' #.SAC .txt
      - cat_columns: ['event_ID','lat','long','depthOrMag','year','month','day','hour','minute','second','magnitudeOrDepth']
      - eventID_string: "path.split('/')[-1].split('.')[-1]"

# Spectrogram parameters
sgramParams:
      - sgramType: "spectrogram"
      - fmin: 8
      - fmax: 20
      - winLen_Sec: 1 #seconds
      - fracOverlap: 1/4
      - nfft: 2000  # padding # isnt this supposed to be a power of 2 ?

      #- sgramType: "scalogram" # if you are using wavelets
      # other wavelet-specific parameters

# SpecUFEx parameters
specufexParams:
      - N_patterns_NMF: 75 # initiate NMF with this many N_patterns (max, then shrinks)
      - N_states_HMM: 15 # number of states for HMM (fixed at this value)

# Clustering parameters
clusteringParams: # toggles are 0=off, 1=on
      - toggleFprints: 1
      - toggleSpectra: 0
      - togglePCs: 0
      - K_vals: [2,3,4,5,6]
      - K_save: 'K_opt' # or [5] a list of ints from K_vals ?


... # three dots ends the yaml file
