---  # three dashes starts the yaml file
# Template for the config file
#

# Paths
paths:
  - key: "project_tag" # for filenames mainly now..
  - projectPath: "put/path/here" # path to the main project directory
  - pathCat: "path/to/catalog/here" # path to where the catalog resides, including the file name
  - pathWF: "path/to/waveform directory/" # path to where the waveform files are
  - h5name: 'setNameforfile.h5' # if we want it to be different from the key !

# Raw data parameters
dataParams:
  - network: 'NC'
  - station: 'BAV'
  - channel: 'EHZ'
  - channel_ID: 0 # the index number for an obspy stream object
  - sampling_rate: 100 # Hz
  - filetype: '.mseed' #.SAC .txt

# Spectrogram parameters
sgramParams:
  - sgramType: "spectrogram"
  - fmin: 8 # minimum frequency in the spectrogram
  - fmax: 20 # maximum frequency in the spectrogram
  - winLen_Sec: 1 # window length in seconds
  - fracOverlap: 1/4 # window overlao fraction
  - nfft: 2000  # padding # isnt this supposed to be a power of 2 ?

#sgramType: "scalogram" # if you are using wavelets - not implemented yet
# other wavelet-specific parameters

# SpecUFEx parameters
specufexParams:
  - N_patterns_NMF: 75 # initiate NMF with this many N_patterns (max, then shrinks)
  - N_states_HMM: 15 # number of states for HMM (fixed at this value)

# Clustering parameters
clusteringParams: # toggles are 0=off, 1=on
toggleFprints: 1
toggleSpectra: 0
togglePCs: 0
K_vals: [2,3,4,5,6]
K_save: 'K_opt' # or [5] a list of ints from K_vals ?


... # three dots ends the yaml file
